# Generated by Django 4.2.15 on 2024-08-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO_web', '0002_consumers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.CharField(max_length=9999999999999999999999999999),
        ),
    ]
